---
abstract: 'local Perl documentation server'
author:
  - 'Jon Allen (JJ) <jj@jonallen.info>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perldoc-Server
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.71001
  Catalyst::View::TT: 0
  Config::General: 0
  File::Monitor: 0
  File::Slurp: 0
  HTML::Entities: 0
  OpenThought: 0
  Perl::Tidy: 0
  Pod::POM: 0.23
  parent: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
